version: '3'
services:

  dummy:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    links:
      - postgres_dummy
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
      - node-volume:/app/node_modules
    command: "bundle exec rails server -b 0.0.0.0"
    user: ${CURRENT_UID}
    stdin_open: true
    tty: true

  webpack-watcher:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
      - node-volume:/app/node_modules
    command: "sh -c 'cd builder && ./bin/webpack --watch'"
    user: ${CURRENT_UID}

  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      RAILS_ENV: test
    links:
      - postgres_test
    ports:
      - "33123:33123"
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
      - node-volume:/app/node_modules
    command: "bundle exec rspec spec/test"
    user: ${CURRENT_UID}

  test_5_2:
    build:
      context: .
      dockerfile: ./Dockerfile.test.5.2
    environment:
      RAILS_ENV: test
    links:
      - postgres_test
    command: "bundle exec rspec spec/test"
    user: ${CURRENT_UID}

  test_6_0:
    build:
      context: .
      dockerfile: ./Dockerfile.test.6.0
    environment:
      RAILS_ENV: test
    links:
      - postgres_test
    command: "bundle exec rspec spec/test"
    user: ${CURRENT_UID}

  test_6_1:
    build:
      context: .
      dockerfile: ./Dockerfile.test.6.1
    environment:
      RAILS_ENV: test
    links:
      - postgres_test
    command: "bundle exec rspec spec/test"
    user: ${CURRENT_UID}

  postgres_dummy:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dummy
    volumes:
      - dummy-data-volume:/var/lib/postgresql/data

  postgres_test:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - test-data-volume:/var/lib/postgresql/data

volumes:
  test-data-volume:
  dummy-data-volume:
  gem-volume:
  node-volume:
