version: 2
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose run --rm test bundle exec rake db:schema:load
            docker-compose run --rm test bundle exec rspec spec/usage