version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=10.0.1-r0
            pip install \
              docker-compose==1.25.3
      - run:
          name: Run tests
          command: |
            docker-compose run --rm test bundle exec rake db:schema:load
            docker-compose run --rm test bundle exec rspec spec/usage